ci: handle timeouts in sample RPC pytest
pytest RPC implementation was not properly handling timeouts, returning
`AttributeError: 'RPCTimeout' object has no attribute 'status_code'`. Add a
check for the timeout exception. The test will still fail but the reason
will be more clear.

Signed-off-by: Mike Szczys <michael.szczys@canonical.com>